/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as ApiPublicSeedRouteImport } from './routes/api/public/seed'
import { Route as AuthenticatedTemplatesSerahTerimaRouteImport } from './routes/_authenticated/templates.serah-terima'
import { Route as AuthenticatedTemplatesAkadRouteImport } from './routes/_authenticated/templates.akad'
import { Route as AuthenticatedDocsMenuRouteImport } from './routes/_authenticated/docs.$menu'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSeedRoute = ApiPublicSeedRouteImport.update({
  id: '/api/public/seed',
  path: '/api/public/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesSerahTerimaRoute =
  AuthenticatedTemplatesSerahTerimaRouteImport.update({
    id: '/templates/serah-terima',
    path: '/templates/serah-terima',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesAkadRoute =
  AuthenticatedTemplatesAkadRouteImport.update({
    id: '/templates/akad',
    path: '/templates/akad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocsMenuRoute = AuthenticatedDocsMenuRouteImport.update({
  id: '/docs/$menu',
  path: '/docs/$menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/docs/$menu': typeof AuthenticatedDocsMenuRoute
  '/templates/akad': typeof AuthenticatedTemplatesAkadRoute
  '/templates/serah-terima': typeof AuthenticatedTemplatesSerahTerimaRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/docs/$menu': typeof AuthenticatedDocsMenuRoute
  '/templates/akad': typeof AuthenticatedTemplatesAkadRoute
  '/templates/serah-terima': typeof AuthenticatedTemplatesSerahTerimaRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/docs/$menu': typeof AuthenticatedDocsMenuRoute
  '/_authenticated/templates/akad': typeof AuthenticatedTemplatesAkadRoute
  '/_authenticated/templates/serah-terima': typeof AuthenticatedTemplatesSerahTerimaRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity-log'
    | '/dashboard'
    | '/trash'
    | '/docs/$menu'
    | '/templates/akad'
    | '/templates/serah-terima'
    | '/api/public/seed'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity-log'
    | '/dashboard'
    | '/trash'
    | '/docs/$menu'
    | '/templates/akad'
    | '/templates/serah-terima'
    | '/api/public/seed'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity-log'
    | '/_authenticated/dashboard'
    | '/_authenticated/trash'
    | '/_authenticated/docs/$menu'
    | '/_authenticated/templates/akad'
    | '/_authenticated/templates/serah-terima'
    | '/api/public/seed'
    | '/_authenticated/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedRoute: typeof ApiPublicSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/seed': {
      id: '/api/public/seed'
      path: '/api/public/seed'
      fullPath: '/api/public/seed'
      preLoaderRoute: typeof ApiPublicSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates/serah-terima': {
      id: '/_authenticated/templates/serah-terima'
      path: '/templates/serah-terima'
      fullPath: '/templates/serah-terima'
      preLoaderRoute: typeof AuthenticatedTemplatesSerahTerimaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/akad': {
      id: '/_authenticated/templates/akad'
      path: '/templates/akad'
      fullPath: '/templates/akad'
      preLoaderRoute: typeof AuthenticatedTemplatesAkadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs/$menu': {
      id: '/_authenticated/docs/$menu'
      path: '/docs/$menu'
      fullPath: '/docs/$menu'
      preLoaderRoute: typeof AuthenticatedDocsMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedDocsMenuRoute: typeof AuthenticatedDocsMenuRoute
  AuthenticatedTemplatesAkadRoute: typeof AuthenticatedTemplatesAkadRoute
  AuthenticatedTemplatesSerahTerimaRoute: typeof AuthenticatedTemplatesSerahTerimaRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedDocsMenuRoute: AuthenticatedDocsMenuRoute,
  AuthenticatedTemplatesAkadRoute: AuthenticatedTemplatesAkadRoute,
  AuthenticatedTemplatesSerahTerimaRoute:
    AuthenticatedTemplatesSerahTerimaRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedRoute: ApiPublicSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
